language: csharp
solution: NRasterizer.sln

install:
  - nuget restore NRasterizer.sln
  - nuget install NUnit.Console -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NRasterizer.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./NRasterizer.Tests/bin/Release/NRasterizer.Tests.dll
 