version: 0.0.{build}
install:
- choco install gitversion.portable -pre -y
  
before_build:
- ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
- cmd: build.cmd
- cmd: build\generate_samples.cmd
    
artifacts:
- path: NOpenType\bin\Release\*.nupkg
- path: samples\**\*.png

deploy:
- provider: S3
  access_key_id: AKIAJSGZDYD54P3KCL3A
  secret_access_key:
    secure: 3hozgs+ePGZ2MaO6OoEHA6bPwvaKRNTb/mEx+ak1/JwJ5I64HfzGGbW8l0iQRZDq
  region: us-west-2
  bucket: nrasterizer-artifacts
  folder: master
  set_public: true

test: off
